#!/bin/sh

if [ "$1" = "purge" ]; then
    deluser --quiet --system elsewhere > /dev/null || true
    delgroup --quiet --system elsewhere > /dev/null || true
    # Cleanup /var/lib/elsewhere
    rm -rf /var/lib/elsewhere > /dev/null 2>&1 || true
fi
