#!/bin/sh

if [ "$1" = "purge" ]; then
    deluser --quiet --system iotic > /dev/null || true
    delgroup --quiet --system iotic > /dev/null || true
    # Cleanup /var/lib/iotic
    rm -rf /var/lib/iotic > /dev/null 2>&1 || true
fi
