#!/bin/sh

#https://stackoverflow.com/questions/71066592/how-to-correctly-add-a-systemd-service-to-a-cpack-generated-debian-package

set -e

case "$1" in
    configure)
    # create iotic user if not there already
    if ! getent passwd iotic >/dev/null; then
        adduser --disabled-password --quiet --system --home /var/lib/iotic --group iotic
    fi
    chown -R iotic:iotic /var/lib/iotic
    #rm -rf /var/lib/iotic/* > /dev/null 2>&1 || true
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0

#DEBHELPER#
