title: iotic
email: mincequi@web.de
description: Iotic streamlines the management of extra solar energy, making it easy to direct and optimize.
github_username: mincequi
theme: just-the-docs

url: https://mincequi.github.io/iotic

# aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

